completed uiapp gh workflow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,11 +1,9 @@
 name: Build VS2022 Extension
 
 on:
-  # push:
-  #   branches: [ main, master ]
-  # pull_request:
-  #   branches: [ main, master ]
-  workflow_dispatch:
+  release:
+    types: [published]
+#   workflow_dispatch:
 
 jobs:
   build:
@@ -14,26 +12,60 @@ jobs:
     env:
       SOLUTION_PATH: 'LHQ_vs2022.sln'
       VSIX_PROJECT_PATH: 'src/VsExtension2022/VsExtension2022.csproj'
-      CONFIGURATION: 'Debug'
+      BUILD_CONFIGURATION: 'Debug'
+      VKP_VERSION: '0.0.1369-g1d5c984'
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v5
 
-    #   - name: Setup .NET
-    #     uses: actions/setup-dotnet@v4
-    #     with:
-    #       dotnet-version: '8.0.x'
+      - name: Setup MSBuild
+        uses: microsoft/setup-msbuild@v2
 
+      - name: Setup NuGet
+        uses: NuGet/setup-nuget@v2
+
+      - uses: pnpm/action-setup@v4
+        name: Install pnpm
+        with:
+          version: 10
+          run_install: false
+
+      - name: Install global tools
+        run: |
+          echo "Installing semver tool"
+          pnpm add -g semver
+
+      - name: Validate release tag value
+        id: validate_tag
+        uses: ./.github/actions/validate-tag
+        with:
+          tag: ${{ github.event.release.tag_name }}
+
+      - name: Update tag environment variables
+        shell: bash
+        run: | 
+          echo "TAG_VERSION=${{ steps.validate_tag.outputs.tag_version }}" >> $GITHUB_ENV
+          echo "TAG_VALID=${{ steps.validate_tag.outputs.tag_valid }}" >> $GITHUB_ENV
+
+      - name: Verify tag validity
+        shell: bash
+        if: env.TAG_VALID == '0'
+        run: |
+          echo "TAG_VALID=${{ env.TAG_VALID }} , TAG_VERSION=${{ env.TAG_VERSION }}"
+          echo "Error: The provided release tag '${{ github.event.release.tag_name }}' is not valid."
+          exit 1
+          
       - name: Check Marketplace for existing version
+        shell: bash
         run: |
           # Extract version from vsixmanifest
           VSIX_MANIFEST="src/VsExtension2022/source.extension.vsixmanifest"
-          TARGET_VERSION=$(grep -oP 'Identity[^>]*Version="\K[^"]+' "$VSIX_MANIFEST")
+          TARGET_VERSION=$(grep -oE 'Identity[^>]*Version="[^"]+' "$VSIX_MANIFEST" | sed -E 's/.*Version="//')
           echo "Target version from manifest: $TARGET_VERSION"
 
-          TARGET_VERSION="2025.2"
-          echo "Using target version: $TARGET_VERSION (for testing purposes)"
+          #   TARGET_VERSION="2025.0"
+          #   echo "Using target version: $TARGET_VERSION (for testing purposes)"
           
           # Visual Studio Marketplace extension identifier
           PUBLISHER="scalehqsolutions"
@@ -77,9 +109,11 @@ jobs:
           # Get the highest version in Marketplace
           highestMarketplaceVersion=$(echo "$versions" | sort -V | tail -n 1)
           echo "Highest version in Marketplace: $highestMarketplaceVersion"
+
+          highestMarketplaceVersion=$(semver -c "$highestMarketplaceVersion")
           
           # Check if Marketplace version is greater than target version
-          isGreater=$(semver "$highestMarketplaceVersion" -r ">$TARGET_VERSION" || echo "false")
+          isGreater=$(semver -c "$highestMarketplaceVersion" -r ">$TARGET_VERSION" || echo "false")
           if [[ "$isGreater" == "$highestMarketplaceVersion" ]]; then
             echo "Error: Marketplace already contains a higher version ($highestMarketplaceVersion) than your manifest ($TARGET_VERSION)."
             exit 1
@@ -88,12 +122,6 @@ jobs:
           echo "Version check passed. Ready to publish version $TARGET_VERSION"
 
           exit 1
-
-      - name: Setup MSBuild
-        uses: microsoft/setup-msbuild@v2
-
-      - name: Setup NuGet
-        uses: NuGet/setup-nuget@v2
 
       - name: Install VsixSignTool and Publish Tool
         run: |
@@ -125,7 +153,7 @@ jobs:
       - name: Build VSIX
         run: |
           msbuild ${{ env.SOLUTION_PATH }} `
-            /p:Configuration=${{ env.CONFIGURATION }} `
+            /p:Configuration=${{ env.BUILD_CONFIGURATION }} `
             /p:DeployExtension=false `
             /p:ZipPackageCompressionLevel=normal `
             /v:minimal
@@ -134,6 +162,12 @@ jobs:
         id: find-vsix
         run: |
           $vsixFile = Get-ChildItem -Path . -Filter *.vsix -Recurse | Select-Object -First 1
+
+          if (-not $vsixFile) {
+            Write-Error "VSIX file not found!"
+            exit 1
+          }
+
           echo "VSIX_PATH=$($vsixFile.FullName)" >> $env:GITHUB_OUTPUT
           echo "VSIX_NAME=$($vsixFile.Name)" >> $env:GITHUB_OUTPUT
 
@@ -161,3 +195,22 @@ jobs:
           name: vsix-package
           path: ${{ steps.find-vsix.outputs.VSIX_PATH }}
           if-no-files-found: error
+          
+      - name: update application version
+        uses: ./.github/actions/update-version
+        with:
+          new_version: ${{ env.TAG_VERSION }}
+          app_project_path: 'src/App/'
+          root_path: '.'
+
+      - name: publish UI App
+        uses: ./.github/actions/uiapp/
+        with:
+          mode: 'publish'
+          vpk_version: ${{ env.VKP_VERSION }}
+          prerelease: ${{ github.event.release.prerelease }}
+          release_name: ${{ github.event.release.name || '' }}
+          release_tag: ${{ github.event.release.tag_name }}
+          new_version: ${{ env.TAG_VERSION }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+
diff --git a/.github/workflows/uiapp.yml b/.github/workflows/uiapp.yml
--- a/.github/workflows/uiapp.yml
+++ b/.github/workflows/uiapp.yml
@@ -8,6 +8,16 @@ on:
         required: false
         default: true
         type: boolean
+      release_tag:
+        description: 'Tag of the release'
+        required: true
+        default: ''
+        type: string
+      release_name:
+        description: 'Name of the release'
+        required: false
+        default: ''
+        type: string
 
 jobs:
   build:
@@ -26,10 +36,51 @@ jobs:
       - name: Setup NuGet
         uses: NuGet/setup-nuget@v2
 
+      - name: Install pnpm
+        uses: pnpm/action-setup@v4
+        with:
+          run_install: false
+          version: 10
+
+      - name: Install dependencies
+        run: |
+          pnpm add -g semver
+
+      - name: Validate release tag value
+        id: validate_tag
+        uses: ./.github/actions/validate-tag
+        with:
+          tag: ${{ github.event.inputs.release_tag || '' }}
+
+      - name: Update tag environment variables
+        shell: bash
+        run: | 
+          echo "TAG_VERSION=${{ steps.validate_tag.outputs.tag_version }}" >> $GITHUB_ENV
+          echo "TAG_VALID=${{ steps.validate_tag.outputs.tag_valid }}" >> $GITHUB_ENV
+
+      - name: Verify tag validity
+        shell: bash
+        if: env.TAG_VALID == '0'
+        run: |
+          echo "TAG_VALID=${{ env.TAG_VALID }} , TAG_VERSION=${{ env.TAG_VERSION }}"
+          echo "Error: The provided release tag '${{ github.event.inputs.release_tag }}' is not valid."
+          exit 1
+
+      - name: update application version
+        uses: ./.github/actions/update-version
+        with:
+          new_version: ${{ env.TAG_VERSION }}
+          app_project_path: 'src/App/'
+          root_path: '.'
+
       - name: Build and Publish UI App
         uses: ./.github/actions/uiapp/
         with:
-          publish_only: 'false'
+          mode: 'build_publish'
           vpk_version: ${{ env.VKP_VERSION }}
           prerelease: ${{ github.event.inputs.prerelease }}
+          release_name: ${{ github.event.inputs.release_name || '' }}
+          release_tag: ${{ github.event.inputs.release_tag || '' }}
+          new_version: ${{ env.TAG_VERSION }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
 
